### PR TITLE
Added tables of contents, logo, documentation for profiles, formats and more

### LINKED ISSUE #36: Add an awesome README
Taking inspiration from https://github.com/matiassingers/awesome-readme let's update our README to be awesome.

### PR DESCRIPTION
**Pull request by bspindler**
closes #36

### CODE REVIEW

**Comment by TheConnMan** [comment]
Will keeping the help console screenshot and command list up to date become a headache or something we forget to do?

**Comment by bspindler** [comment]
Probably.  Right now, I was trying to strike that balance and I started writing content for each Command but it seemed like a waste at this point.  
It might make sense for some like `package validate` and others.
Over time I expect the overall readme to become more objective based, such as 
- Searching for elements
- Searching for metrics
- Querying for data
- Integrating Packages into your build pipeline
and so on... 
but for now this highlights the capabilities nicely without adding too much doc maintenance burden.
I could be convinced to remove the help screenshot, I just like highlighting it cause I think it looks great and makes the cli immediately understandable. 

I would love to replace it with a screen terminal recording of executing help, then some other commands to demonstrate, that would be awesome.  I could not get asciicinema working when I took a quick shot at it.

**Comment by TheConnMan** [comment]
I like the screenshot or gif as long as it's an example and we don't expect it to stay updated unless there are major changes. The list of commands replicates the CLI help list, so I think it should be removed from the docs, it's just duplication. We've made installation of the CLI extremely easy, so downloading it and running `metricly` to see the current commands is a small investment. Maybe we can keep the top level domain objects you can interact with (dashboards, packages, policies) up to date in the docs, just not the individual subcommands.

**Comment by bspindler** [comment]
Agreed.  Let's leave the screenshot just for help, no need to commit to updating all the time.  LMK if you think this works then for a first pass.

**Comment by TheConnMan** [comment]
Works for me. Do you need to remove the links to commands in the table of contents?

**Pull request merged**
